# Generated by Django 5.2.9 on 2026-01-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_subcategory_item_subcategory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', True)), fields=('category', 'name'), name='unique_direct_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('subcategory', 'name'), name='unique_subcategory_item_idx'),
        ),
    ]
