# Generated by Django 5.2.9 on 2026-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_item_unique_direct_item_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Cached popularity score (frequency of use)'),
        ),
    ]
