# Generated by Django 5.2.9 on 2026-02-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0004_item_usage_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-usage_count', 'name']},
        ),
    ]
