# Generated by Django 5.2.9 on 2026-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='average_stock',
            field=models.FloatField(default=0, help_text='Ideal stock level for calculation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='usage_count',
            field=models.FloatField(default=0, help_text='Cached popularity score (frequency of use)'),
        ),
    ]
