from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('category/<int:category_id>/', views.view_category, name='view_category'),
    path('subcategory/<int:subcategory_id>/', views.view_subcategory, name='view_subcategory'),
    path('take/<int:item_id>/', views.take_item, name='take_item'),
    path('today/', views.today, name='today'),
    path('consumption/<int:record_id>/delete/', views.delete_consumption, name='delete_consumption'),
    path('stock/', views.stock_list, name='stock_list'),
    path('stock/low/', views.low_stock_list, name='low_stock_list'),
    path('stock/<int:item_id>/update/', views.update_stock, name='update_stock'),
    path('manage/categories/', views.manage_categories, name='manage_categories'),
    path('manage/category/add/', views.add_category, name='add_category'),
    path('manage/category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('manage/category/<int:category_id>/edit/', views.edit_category, name='edit_category'),
    path('manage/category/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('manage/category/<int:category_id>/add_subcategory/', views.add_subcategory, name='add_subcategory'),
    path('manage/subcategory/<int:subcategory_id>/edit/', views.edit_subcategory, name='edit_subcategory'),
    path('manage/subcategory/<int:subcategory_id>/delete/', views.delete_subcategory, name='delete_subcategory'),
    path('manage/category/<int:category_id>/add_item/', views.add_item, name='add_item'),
    path('manage/items/<int:item_id>/edit/', views.edit_item, name='edit_item'),
    path('manage/items/<int:item_id>/delete/', views.delete_item, name='delete_item'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.profile, name='profile_view'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('manage/staff/', views.manage_staff, name='manage_staff'),
    path('manage/history/', views.stock_history, name='stock_history'),
    path('manage/staff/add/', views.add_staff, name='add_staff'),
    path('manage/staff/<int:user_id>/edit/', views.edit_staff, name='edit_staff'),
    path('manage/staff/<int:user_id>/delete/', views.delete_staff, name='delete_staff'),
]